config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :projects
  devise_for :users
  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/views/index/_footer.html.erb
<footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Lemonade</strong> Amazing app
      </p>
    </div>
  </footer>

app/views/index/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a
      role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbarTop"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarTop" class="navbar-menu">
    <% if  user_signed_in?%>
      <div class="navbar-start">
        <div class="dropdown is-hoverable">
          <a class="navbar-item">
            <ion-icon name="add" class="mr-1"></ion-icon>
            New
          </a>
          <div class="dropdown-menu box has-background-dark pt-3" id="dropdown-menu">
            <%= link_to "Test Cases", new_test_path, :class => "navbar-item has-text-white-bis dp-navbar-item" %>
            <a class="navbar-item has-text-white-bis dp-navbar-item">
              Test Plan
            </a>
            <a class="navbar-item has-text-white-bis dp-navbar-item">
              Test Execution
            </a>
          </div>
        </div>
        <a class="navbar-item"> Settings </a>
        <%= link_to "Tests", root_path, :class => "navbar-item" %>
        <a class="navbar-item"> Reports </a>
      </div>
    <% else %>
      <div class="navbar-start">
        <%= link_to "Home", root_path, :class => "navbar-item" %>
        <a class="navbar-item"> Documentation </a>
      </div>
    <% end %>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%- unless user_signed_in? %>
            <%= button_to("Log in", user_session_path, method: :post, :class => "button is-light" ) %>
            <%= button_to("Sign up", new_user_registration_path, method: :get, :class => "button is-primary"  ) %>
          <% end %>
          <%- if user_signed_in?%>
            <%= button_to("Log Out", destroy_user_session_path, method: :delete, :class => "button is-primary"  ) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/index/_home_pagination.html.erb
<% unless @test_cases.nil? %>
    <%= paginate @test_cases %>
<% end %>

app/views/index/_panel.html.erb
<article class="panel is-primary">
  <p class="panel-heading">
    Projects
  </p>


  <div class="panel-block">
    <p class="control has-icons-left">
      <input class="input is-primary" type="text" placeholder="Search">
      <span class="icon is-left">
        <i class="fas fa-search" aria-hidden="true"></i>
      </span>
    </p>
  </div>

  <% if !@project_list.blank? %>
    <% for project in @project_list %>

      <a class="panel-block is-active" href=<%= "?project=#{project.projectId}" %> >
        <span class="panel-icon">
            <ion-icon name="briefcase"></ion-icon>
        </span>

            <%=  project.name %>
            <% unless project.isPrivate %>
                <span class="tag is-primary is-light is-rounded ml-1">Shared</span>
            <% end %>
           
      </a>
      
    <% end %>
  <% end %>



    <div class="panel-block is-flex-direction-column">
      <button id="project_settings_bt" class="button is-light is-fullwidth mb-1">
        Join a Project
      </button>
      <button id="new_prject_bt" class="button is-primary is-fullwidth mt-1">
        New Project
      </button>
    </div>
  </article>
  <%= render 'index/panel_modal'%>

app/views/index/_panel_modal.html.erb
<div id="new_project_modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">

    <header class="modal-card-head">
      <p class="modal-card-title">New Project</p>
      <button class="delete remove_new_project_modal" aria-label="close"></button>
    </header>

    <%= render :partial => "projects/form", project: @project %>
  </div>
</div>


<%# <div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Modal title</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <button class="button is-success">Save changes</button>
      <button class="button">Cancel</button>
    </footer>
  </div>
</div> %>

app/views/index/_tabs.html.erb
<div class="tabs is-centered is-toggle ">
  <ul>
    <li class="is-active">
      <a>
      <span class="icon is-small">
        <ion-icon name="beaker"></ion-icon>
        </span>
        <span>Test Cases</span>
      </a>
    </li>
    <li>
      <a>
      <span class="icon is-small">
        <ion-icon name="document"></ion-icon>
        </span>
        <span>Test Plan</span>
      </a>
    </li>
    <li>
      <a>
      <span class="icon is-small">
        <ion-icon name="construct"></ion-icon>
        </span>
        <span>Test Execution</span>
      </a>
    </li>
  </ul>
</div>

app/views/index/_test_cases.html.erb
<div class="box">
  <table class="table table-test-cases is-fullwidth">
    <thead>
      <tr>
        <th><abbr title="Test Id">Id</abbr></th>
        <th><abbr title="Test name">Test</abbr></th>
        <th><abbr title="Number of steps in the test">Steps</abbr></th>
        <th><abbr title="The Test Creation date ">Created on</abbr></th>
        <th><abbr title="Test Tag">Tag</abbr></th>
        <th><abbr title="Test Last Run Status">Status</abbr></th>
      </tr>
    </thead>
    <tbody>

      <% if !@test_cases.blank? %>
        <% for tests in @test_cases %>
          <tr class= 'test-case-row' 
          link='<%= "#{test_path(tests)}?project=#{params[:project]}"%>' > 
            <th> <%= tests.id %> </th>
            <td><%= tests.name %></td>
            <td>UPDATE</td>
            <td> <%= tests.created_at %></td>
            <td><%= tests.tag %></td>

            <% case tests.status
                 when nil %>
            <td>
              <span class="tag is-warning" title="">
                <ion-icon name="remove-circle-outline" ></ion-icon>
              </span>
            </td>

            <% when 'passed' %>
            <td>
              <span class="tag is-primary" title="Passed">
                <ion-icon name="checkmark-done"></ion-icon>
              </span>
            </td>

            <% when 'failed' %>
            <td>
              <span class="test-status-failed tag is-danger">
                <ion-icon name="close-outline"></ion-icon>
              </span>
            </td>

          <% else %>
            <td>
              <span class="tag is-warning" title="">
                <ion-icon name="remove-circle-outline" ></ion-icon>
              </span>
            </td>
          <% end %>

        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

  <% if @test_cases.blank? %>

  <div class="notification is-primary  is-light is-flex is-align-items-center is-justify-content-center is-3">
    <ion-icon name="information-circle-outline" size='large' class='m-2'>
    </ion-icon>
    <div>
      <%=
        ['It is lonely here, no tests to play with.',
        'Oopsy daisy.. no tests, it is crazy!',
        'No test cases to display.'
        ].sample
      %>
      Select a project from the side panel or create a <%= link_to "test case", new_test_path %>
    </div>
  </div>

  <% end %>


</div>

app/views/index/home.html.erb
<div class="tile is-ancestor p-2 pt-6 pb-6s">

  <div class="tile is-3 is-vertical is-parent">
    <%= render 'index/panel' %>
  </div>

  <div class="tile is-vertical is-fullwidth is-parent">
    <div class="tile is-child top-tabs" >
      <%= render 'index/tabs'%>
    </div>

    <div class="tile is-child">
      <%= render 'index/test_cases'%>
    </div>

    <div class="tile is-child">
      <%= render 'index/home_pagination'%>
    </div>
  </div>
</div>