config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :projects
  devise_for :users
  get 'index/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#home"
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tests
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.projectId = SecureRandom.uuid

    respond_to do |format|
      if @project.save && set_prject_owner(@project.id)
        format.html { redirect_to root_path, notice: "Project: #{@project.name} was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :isPrivate)
    end

    def set_prject_owner(project_id)
      ProjectUser
      .new(projectId:project_id , userId: current_user.id, accessLevel: 'owner')
      .save
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  
    def validate_uuid_format(uuid)
        uuid_regex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
        uuid_regex.match?(uuid.to_s.downcase)
    end

    
    
    def get_project_id(project_uuid, project_list)
        is_valid_project_id = validate_uuid_format(project_uuid)
    
              if is_valid_project_id
                project_list
                  .filter{|project| project.projectId.eql? project_uuid}
                  &.first
                  &.id
              else 
                nil 
              end
    end

    def is_project_contains_test(test_id, project_id)
      !Test
      .where(project_Id: project_id, id: test_id)
      .empty?
    end

    def is_project_owner(user_id, project_id)
      !ProjectUser
      .where(projectId: project_id, userId: user_id, accessLevel: 'owner' )
      .empty?
    end


    def is_project_guest(user_id, project_id)
      !ProjectUser
      .where(projectId: project_id, userId: user_id, accessLevel: 'guest' )
      .empty?
    end

end

app/views/projects/_form.html.erb
  <section class="modal-card-body">

  <div class="notification is-info is-light is-flex is-align-items-center is-3">
    <ion-icon name="information-circle-outline" size='large' class='m-2'>
    </ion-icon>
    <div>
      You can configure your project in <strong> settings </strong> when its created
    </div>
  </div>

  <%= form_with(model: @project) do |form| %>
    <% if @project.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
        <ul>
          <% @project.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label "project name", style: "display: block", :class => "label" %>
      <%= form.text_field :name, :class => "input" %>
    </div>
   
    <div class="field">
      <%= form.label :description, style: "display: block", :class => "label" %>
      <%= form.text_field :description, :class => 'input' %>
    </div>
   

   <div class="field">
      <label class="checkbox">
       <%= form.check_box :isPrivate, :class => 'checkbox' %>
        This is a private project 
      </label>
    </div>


    <br/>
    <div>
      <%= form.submit "Save new porject", :class => 'button is-primary' %>
    </div>

  <% end %>
</section>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Isprivate:</strong>
    <%= project.isPrivate %>
  </p>

  <p>
    <strong>Projectid:</strong>
    <%= project.projectId %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>